print("Hey Young World")
print("run the code don't let the code run you")
print("the IDE keeps crashing and its driving me nuts")
print("but proof of work is important. They say the 5th time is the charm")
print("learn as much as you can as fast as you can.")
print("teach others along the way if you can.")